---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: Check if Image Variable Exists
      stat:
        path: '/opt/communityapps'
      register: pathcheck

    - name: 'Transfer Image Variable'
      shell: 'rm -rf /opt/communityapps'
      when: pathcheck.stat.exists

    - name: Cloning Community Apps
      git:
        repo: 'https://github.com/MHA-Team/Apps-Community'
        dest: /opt/communityapps
        version: 'master'
        force: yes

    - name: Set Permission and Owner 
      shell: 'chown -R 1000:1000 /opt/communityapps && chmod -R 775 /opt/communityapps'
