#!/bin/bash
#
################################################################################
---
- hosts: localhost
  gather_facts: false
  tasks:
    # FACTS #######################################################################
    - name: 'Set Known Facts'
      set_fact:
        pgrole: 'plexautoscan'
        intport: '3030'
        extport: '3030'
        image: 'cloudb0x/autoscan:master'

    # CORE (MANDATORY) ############################################################
    - name: 'Including cron job'
      include_tasks: './core.yml'

    - name: 'Including PAS Tasks'
      include_tasks: './pastask.yml'

    # LABELS ######################################################################
    - name: 'Adding Traefik for {{pgrole}}'
      set_fact:
        pg_labels:
          traefik.enable: 'true'
          traefik.port: '{{intport}}'
          traefik.frontend.auth.forward.address: '{{gauth}}'
          traefik.frontend.rule: 'Host:{{pgrole}}.{{domain.stdout}}'
          traefik.frontend.headers.SSLHost: '{{domain.stdout}}'
          traefik.frontend.headers.SSLRedirect: 'true'
          traefik.frontend.headers.STSIncludeSubdomains: 'true'
          traefik.frontend.headers.STSPreload: 'true'
          traefik.frontend.headers.STSSeconds: '315360000'
          traefik.frontend.headers.browserXSSFilter: 'true'
          traefik.frontend.headers.contentTypeNosniff: 'true'
          traefik.frontend.headers.customResponseHeaders: 'X-Robots-Tag:noindex,nofollow,nosnippet,noarchive,notranslate,noimageindex'
          traefik.frontend.headers.forceSTSHeader: 'true'

    ## Anchors ###########################################################-07-09-2021
    - name: 'Create {{pgrole}} folders'
      file: "path={{ item }} state=directory mode=0775 owner=1000 group=1000 recurse=yes"
      with_items:
        - '/opt/appdata/{{pgrole}}'
        - '/mnt/unionfs/.anchors/'

    - name: 'Create {{pgrole}} anchors file'
      file: "path={{ item }} state=touch mode=0775 owner=1000 group=1000"
      with_items:
        - '/mnt/unionfs/.anchors/cloud.anchor'
        - '/mnt/unionfs/.anchors/local.anchor'


    ## ConfigFile ###########################################################-07-09-2021
    - name: 'Checking for existing {{pgrole}}/config.yml'
      stat:
        path: /opt/appdata/{{pgrole}}/config.yml
      register: confcheck

    - name: 'Creating {{pgrole}}/config.yml'
      file: "path={{ item }} state=file mode=0775 owner=1000 group=1000 recurse=yes"
      with_items:
        - '/opt/appdata/{{pgrole}}/config.yml'
      ignore_errors: yes
      when: confcheck.stat.exists == false

    # Volumes ######################################################################
    - name: 'Setting {{pgrole}} Volumes'
      set_fact:
        pg_volumes:
          - '/mnt/unionfs/:/data'
          - '/opt/appdata/plexguide:/rclone_config'
          - '/opt/appdata/{{pgrole}}/config:/config'
          - '/opt/appdata/plex/database/Library/Application Support/Plex Media Server/Plug-in Support/Databases/:/plexDb'
          - '{{path.stdout}}:{{path.stdout}}'
          - '/etc/localtime:/etc/localtime:ro'
          - '/var/run/docker.sock:/var/run/docker.sock'

    # Env ######################################################################      
    - name: 'Setting {{pgrole}} ENV'
      set_fact:
        pg_env:
          PUID: '1000'
          PGID: '1000'
          AUTOSCAN_VERBOSITY: '1'

    # MAIN DEPLOYMENT #############################################################
    - name: 'Deploying {{pgrole}}'
      docker_container:
        name: '{{pgrole}}'
        image: '{{image}}'
        pull: yes
        published_ports:
          - '{{ports.stdout}}{{extport}}:{{intport}}'
        volumes: '{{pg_volumes}}'
        env: '{{pg_env}}'
        restart_policy: unless-stopped
        networks:
          - name: plexguide
            aliases:
              - '{{pgrole}}'
        state: started
        labels: '{{pg_labels}}'

    - debug: msg="Final Notes = Plex AutoScan PAGE  {{pgrole}}.{{domain.stdout}}/{{plex_autoscan_server_pass.stdout}}"
