#!/bin/bash
#
# Title:      PTS List commands
# Author(s):  Pandaura
# GNU:        General Public License v3.0
################################################################################
ANSIBLE_CONFIG=menu\alias\ansible.cfg
---
- hosts: localhost
  gather_facts: false
  tasks:
    ###### Install PTSupdate

    - name: PTSupdate | part 1
      template:
        src: ptsupdate
        dest: /bin/ptsupdate
        no_log: true
        force: yes
        mode: 0775

    - name: PTSupdate | part 2
      template:
        src: autoupdatepts
        dest: /bin/autoupdatepts
        no_log: true
        force: yes
        mode: 0775

    ###### Install PGBlitz

    - name: PlexGuide
      template:
        src: plexguide
        dest: /bin/plexguide
        no_log: true
        force: yes
        mode: 0775
        owner: root

    - name: PTS
      template:
        src: pts
        dest: /bin/pts
        no_log: true
        force: yes
        mode: 0775
        owner: root

    - name: PGBlitz
      template:
        src: pgblitz
        dest: /bin/pgblitz
        no_log: true
        force: yes
        mode: 0775
        owner: root

    ###### Server reboot

    - name: server reboot
      template:
        src: reboot
        dest: /bin/reboot
        no_log: true
        force: yes
        mode: 0775

    ###### Check list of services

    - name: list systemd services
      template:
        src: slist
        dest: /bin/slist
        no_log: true
        force: yes
        mode: 0775
        owner: root

    - name: list pts commands
      template:
        src: scommands
        dest: /bin/scommands
        no_log: true
        force: yes
        mode: 0775
        owner: root

    ###### Server update

    - name: update server
      template:
        src: update
        dest: /bin/update
        no_log: true
        force: yes
        mode: 0775

    ###### Server upgrade

    - name: upgrade server
      template:
        src: upgrade
        dest: /bin/upgrade
        no_log: true
        force: yes
        mode: 0775
        owner: root

    ###### Install app

    - name: install appname
      template:
        src: install
        dest: /bin/install
        no_log: true
        force: yes
        mode: 0775
        owner: root

    ###### Autoremove installed app packages

    - name: autoremove unused packages after app install
      template:
        src: autoremove
        dest: /bin/autoremove
        no_log: true
        force: yes
        mode: 0775
        owner: root

    - name: Prune docker containers appname
      template:
        src: prune
        dest: /bin/prune
        no_log: true
        force: yes
        mode: 0775
        owner: root

    - name: Install PTS-User ADD
      template:
        src: ptsadd
        dest: /bin/ptsadd
        no_log: true
        force: yes
        mode: 0775

    - name: Install rclone updater
      template:
        src: rcupdate
        dest: /bin/rcupdate
        no_log: true
        force: yes
        mode: 0775

    - name: Install mergerfes updater
      template:
        src: mgupdate
        dest: /bin/mgupdate
        no_log: true
        force: yes
        mode: 0775

    - name: Install Backup & Restore
      template:
        src: backup
        dest: /bin/backup
        no_log: true
        force: yes
        mode: 0775

    - name: GCE 
      template:
        src: gce
        dest: /bin/gce
        no_log: true
        force: yes
        mode: 0775

    - name: purge old Journal files
      template:
        src: jpurge
        dest: /bin/jpurge
        no_log: true
        force: yes
        mode: 0775

    - name: purge old log files
      template:
        src: kill_logs
        dest: /bin/kill_logs
        no_log: true
        force: yes
        mode: 0775

    - name: automatic backup /opt/appdata 
      template:
        src: autobackup
        dest: /bin/autobackup
        no_log: true
        force: yes
        mode: 0775

    - name: automatic speedtest over speedtest.net
      template:
        src: ptsspeed
        dest: /bin/ptsspeed
        no_log: true
        force: yes
        mode: 0775