---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: 'Check folder exist'
      stat:
        path: /opt/pgstage
      register: stat_result
    - debug:
        msg: "PTS Check for missing pull"

    - name: 'Cloning PTS Install files'
      git:
        repo: 'https://github.com/MHA-Team/Install'
        dest: '/opt/pgstage'
        clone: yes
        version: 'master'
        force: yes
        update: yes
      become: yes

    - stat:
        path: /opt/pgstage
      register: p
    - debug:
        msg: "Path exists and PTS folder are pulled"
      when: p.stat.isdir is defined and p.stat.isdir

    - name: Remove .githube folder and .git files
      file: 'path={{item}} state=absent mode=0775 owner=1000 group=1000'
      with_items:
        - '/opt/pgstage/.git'
        - '/opt/pgstage/.github'
        - '/opt/pgstage/.gitignore'
        - '/opt/pgstage/LICENSE'
        - '/opt/pgstage/README.md'